version: '1'
services:
  media-srv:
    image: media-srv
#    command: tail -F /dev/null
    environment:
      - TZ=Asia/Shanghai
      - PORT=8860
      - REDIS_HOST=hsredis
      - REDIS_PASSWORD=highsai
      - REDIS_PORT=6379
      - CONVERT_URL=http://172.16.180.51:18000/v1/audio/transcriptions
      - CALLBACK_URL=http://172.16.180.98:8080/api/any/receive-subtitles
#      - CALLBACK_URL=http://172.16.80.199:8861/api/test
      - MODEL_URL=http://172.16.110.70:23333/v1/oai/completions
      - MODEL_URL_BASE=http://172.16.110.70:23333/v1
    ports:
      - 8860:8860
    volumes:
      - ./uploadFile:/app/upload
    depends_on:
      - hsredis
    restart: always

  hsredis:
    image: redis
    command: redis-server --requirepass highsai
    ports:
      - 6379:6379
    restart: always
